Repository googleapis/nodejs-promisify, pull requests merged in 2019-02, with the labels that each got.

#83 docs: add lint/fix example to contributing guide
  .github/CONTRIBUTING.md
Labels: cla: yes

#85 chore: move CONTRIBUTING.md to root
  CONTRIBUTING.md
Labels: cla: yes

#86 docs: update contributing path in README
  README.md
Labels: cla: yes

#87 build: test using @grpc/grpc-js in CI
  .kokoro/continuous/node8/system-test-grpcjs.cfg
  .kokoro/presubmit/node8/system-test-grpcjs.cfg
Labels: cla: yes

#88 build: create docs test npm scripts
  .kokoro/docs.sh
  package.json
Labels: cla: yes

#82 feat: add callbackify() and callbackifyAll() methods
  README.md
  src/index.ts
  test/index.ts
Labels: :rotating_light:, cla: yes

#89 Release @google-cloud/promisify v0.4.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#91 docs: update links in contrib guide
  CONTRIBUTING.md
Labels: cla: yes

#90 build: use linkinator for docs test
  package.json
Labels: cla: yes
