Repository googleapis/nodejs-promisify, pull requests merged in 2020-05, with the labels that each got.

#198 chore: unpin version of gts
  package.json
Labels: automerge, cla: yes

#197 chore: update npm scripts and synth.py
  package.json
  synth.py
  tsconfig.json
Labels: automerge, cla: yes

#199 chore: linting rules
  synth.metadata
  system-test/system.ts
Labels: automerge, cla: yes, context: none

#200 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
